#
# Created: 10th August 2026
# Updated: 10th August 2026
#

name: CI

on:
  push:
    branches:
    - master
    - dev
    - ci
    - release-*
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out code
      uses: actions/checkout@v4

    - name: Shell syntax
      run: bash -n unix/.commonrc
